/********************************************************************************
** Form generated from reading UI file 'interface1.ui'
**
** Created by: Qt User Interface Compiler version 5.9.9
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_INTERFACE1_H
#define UI_INTERFACE1_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QCalendarWidget>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDateEdit>
#include <QtWidgets/QFrame>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHBoxLayout>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTableView>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_interface1
{
public:
    QWidget *centralwidget;
    QStackedWidget *stackedWidget;
    QWidget *page;
    QTabWidget *tabWidget;
    QWidget *tab;
    QGroupBox *groupBox;
    QLabel *label_2;
    QLabel *label_3;
    QLabel *label_4;
    QLabel *label_5;
    QLabel *label_6;
    QLabel *label_7;
    QLabel *label_8;
    QLineEdit *le_matricule;
    QLineEdit *le_nom;
    QLineEdit *le_prenom;
    QLineEdit *le_numero_de_cin;
    QLineEdit *le_adresse_email;
    QLineEdit *le_numero_de_telephone;
    QPushButton *pushButton;
    QLabel *label_9;
    QLineEdit *le_sexe;
    QLabel *label_nomControl;
    QLabel *label_prenomControl;
    QLabel *label_cinControl;
    QLabel *label_dateControl;
    QLabel *label_sexeControl;
    QLabel *label_adresse_emailControl;
    QLabel *label_telephoneControl;
    QLabel *label_matriculeControl;
    QLineEdit *lineEditpass;
    QLabel *label_pass;
    QLabel *label_21;
    QDateEdit *le_date_de_naissance;
    QLabel *label_20;
    QDateEdit *date;
    QPushButton *pushButton_qu;
    QWidget *tab_2;
    QTableView *tab_employe;
    QLineEdit *lineEdit_rechercher;
    QComboBox *comboBoxTri;
    QCheckBox *checkBox;
    QCheckBox *checkBox_2;
    QPushButton *pushButton_3;
    QPushButton *pushButton_7;
    QPushButton *pushButton_8;
    QLabel *label_45;
    QPushButton *pushButton_arduino;
    QWidget *tab_3;
    QLineEdit *lespp;
    QLabel *label_10;
    QPushButton *pb_supprimer;
    QLabel *label_suppControl;
    QLabel *label_46;
    QWidget *tab_4;
    QGroupBox *groupBox_2;
    QLabel *label_11;
    QLabel *label_12;
    QLabel *label_13;
    QLabel *label_14;
    QLabel *label_15;
    QLabel *label_16;
    QLabel *label_17;
    QLineEdit *le_matricule_2;
    QLineEdit *le_nom_2;
    QLineEdit *le_prenom_2;
    QLineEdit *le_numero_de_cin_2;
    QLineEdit *le_adresse_email_2;
    QLineEdit *le_numero_de_telephone_2;
    QPushButton *pushButton_2;
    QLabel *label_18;
    QLineEdit *le_sexe_2;
    QComboBox *comboBox;
    QLabel *label_matriculeControl2;
    QLabel *label_nomControl2;
    QLabel *label_prenomControl2;
    QLabel *label_cinControl2;
    QLabel *label_dateControl2;
    QLabel *label_sexeControl2;
    QLabel *label_adresse_emailControl2;
    QLabel *label_telephoneControl2;
    QLabel *label_20pass2;
    QLineEdit *lineEditpass2;
    QLabel *label_202;
    QDateEdit *le_date_de_naissance_2;
    QLabel *date1;
    QDateEdit *dateEdit;
    QLabel *label_47;
    QWidget *tab_5;
    QFrame *horizontalFrame;
    QHBoxLayout *horizontalLayout;
    QPushButton *pushButton_16;
    QLabel *label_53;
    QWidget *tab_6;
    QCalendarWidget *calendarWidget;
    QLabel *label_52;
    QWidget *page_5;
    QTabWidget *tabWidget_3;
    QWidget *tab_13;
    QGroupBox *groupBox_6;
    QLabel *label_56;
    QLineEdit *le_marque;
    QLabel *label_57;
    QLineEdit *le_modele;
    QLabel *label_59;
    QLineEdit *le_afb;
    QLabel *label_58;
    QLineEdit *le_plaque_dimmat;
    QLabel *label_60;
    QLineEdit *le_kilometrage;
    QLabel *label_61;
    QLineEdit *le_etat;
    QLabel *label_62;
    QLineEdit *le_tarifs;
    QPushButton *ajouter_vo;
    QPushButton *modifier_2;
    QPushButton *stat_sarah;
    QPushButton *pdf_sara;
    QPushButton *qrcode;
    QGroupBox *groupBox_9;
    QLineEdit *dateTimeEditConfig;
    QPushButton *OK;
    QPushButton *pushButton_20;
    QWidget *tab_14;
    QTableView *affichertab;
    QLabel *label_63;
    QLineEdit *cherche;
    QPushButton *chercher_sara;
    QPushButton *pushButton_trianne;
    QPushButton *tarifs;
    QTableView *tab_tri;
    QPushButton *pushButton_trianne_2;
    QWidget *tab_15;
    QGroupBox *groupBox_7;
    QLabel *label_64;
    QLineEdit *lineEdit_8;
    QPushButton *supp_sara;
    QWidget *tab_18;
    QGroupBox *groupBox_8;
    QLabel *label_72;
    QLineEdit *lineEditPlaqueImmatriculation;
    QLabel *aff;
    QPushButton *kilometrage;
    QPushButton *pushButton_22;
    QWidget *page_4;
    QTabWidget *tabWidget_2;
    QWidget *tab_7;
    QGroupBox *groupBox_4;
    QLabel *label_22;
    QLabel *label_23;
    QLabel *label_24;
    QLabel *label_25;
    QLabel *label_26;
    QLabel *label_27;
    QLabel *label_28;
    QLabel *label_29;
    QLineEdit *lineEdit_NOM;
    QLineEdit *lineEdit_PRENOM;
    QLineEdit *lineEdit_ADRESSE;
    QLineEdit *lineEdit_ADRESSEEMAIL;
    QLineEdit *lineEdit_NUMPERMIS;
    QLineEdit *lineEdit_NUMTEL;
    QLineEdit *lineEdit_NUMCIN;
    QPushButton *pushButton_10;
    QDateEdit *lineEdit_NAISSANCE;
    QLabel *label_48;
    QPushButton *pushButton_17;
    QWidget *tab_8;
    QTableView *tableView;
    QTableView *tableView_2;
    QPushButton *pushButton_11;
    QPushButton *pushButton_12;
    QPushButton *pushButton_13;
    QLineEdit *rechercher;
    QLabel *label_49;
    QWidget *tab_9;
    QLineEdit *lineEdit_2;
    QLabel *label_30;
    QPushButton *pushButton_14;
    QLabel *label_50;
    QWidget *tab_10;
    QGroupBox *groupBox_5;
    QLineEdit *lineEdit_nom;
    QLineEdit *lineEdit_prenom;
    QLineEdit *lineEdit_numpermis;
    QLineEdit *lineEdit_adresse;
    QLineEdit *lineEdit_email;
    QLineEdit *lineEdit_numtel;
    QLineEdit *cinToModifyLineEdit;
    QPushButton *pushButton_15;
    QLabel *label_31;
    QLabel *label_32;
    QLabel *label_33;
    QLabel *label_34;
    QLabel *label_35;
    QLabel *label_36;
    QLabel *label_37;
    QLabel *label_38;
    QDateEdit *lineEdit_naissance;
    QLabel *label_51;
    QWidget *tab_11;
    QFrame *frame;
    QWidget *tab_12;
    QPushButton *pushButton_19;
    QLineEdit *lineEditcl;
    QLineEdit *lineEdit_3;
    QLabel *label_54;
    QLabel *label_55;
    QWidget *page_2;
    QGroupBox *groupBox_3;
    QLineEdit *lineEdit_username;
    QLineEdit *lineEdit_password;
    QLabel *label;
    QLabel *label_19;
    QPushButton *pushButton_5;
    QPushButton *pushButton_6;
    QLabel *label_39;
    QLabel *label_40;
    QWidget *page_3;
    QPushButton *pushButton_4;
    QPushButton *pushButton_9;
    QLabel *label_41;
    QLabel *label_42;
    QLabel *label_43;
    QPushButton *pushButton_18;
    QPushButton *pushButton_21;
    QPushButton *pushButton_23;
    QWidget *page_6;
    QPushButton *contrat_a;
    QGroupBox *groupBox_10;
    QLabel *label_44;
    QLabel *label_65;
    QLabel *label_66;
    QLabel *label_67;
    QLineEdit *CONTRATID;
    QPushButton *ajouter;
    QPushButton *modifier;
    QPushButton *supprimer;
    QPushButton *afficher;
    QLineEdit *MONTANT;
    QDateEdit *DATEDEBUT;
    QDateEdit *DATEFIN;
    QPushButton *pdf;
    QPushButton *stattt;
    QPushButton *tri_3;
    QLineEdit *chercher;
    QTableView *tableViewHistorique;
    QLineEdit *id_ca;
    QPushButton *historique;
    QPushButton *tri_2;
    QTableView *affiche_tab;
    QPushButton *tri;
    QLabel *label_68;

    void setupUi(QMainWindow *interface1)
    {
        if (interface1->objectName().isEmpty())
            interface1->setObjectName(QStringLiteral("interface1"));
        interface1->resize(1297, 707);
        centralwidget = new QWidget(interface1);
        centralwidget->setObjectName(QStringLiteral("centralwidget"));
        stackedWidget = new QStackedWidget(centralwidget);
        stackedWidget->setObjectName(QStringLiteral("stackedWidget"));
        stackedWidget->setGeometry(QRect(0, 0, 1271, 691));
        page = new QWidget();
        page->setObjectName(QStringLiteral("page"));
        tabWidget = new QTabWidget(page);
        tabWidget->setObjectName(QStringLiteral("tabWidget"));
        tabWidget->setGeometry(QRect(120, 30, 791, 481));
        tab = new QWidget();
        tab->setObjectName(QStringLiteral("tab"));
        groupBox = new QGroupBox(tab);
        groupBox->setObjectName(QStringLiteral("groupBox"));
        groupBox->setGeometry(QRect(210, 70, 411, 331));
        label_2 = new QLabel(groupBox);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(20, 30, 56, 21));
        label_3 = new QLabel(groupBox);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(20, 60, 56, 16));
        label_4 = new QLabel(groupBox);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(20, 90, 56, 16));
        label_5 = new QLabel(groupBox);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(20, 120, 91, 16));
        label_6 = new QLabel(groupBox);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(20, 150, 111, 16));
        label_7 = new QLabel(groupBox);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(20, 210, 81, 16));
        label_8 = new QLabel(groupBox);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(20, 240, 131, 16));
        le_matricule = new QLineEdit(groupBox);
        le_matricule->setObjectName(QStringLiteral("le_matricule"));
        le_matricule->setGeometry(QRect(160, 30, 113, 22));
        le_nom = new QLineEdit(groupBox);
        le_nom->setObjectName(QStringLiteral("le_nom"));
        le_nom->setGeometry(QRect(160, 60, 113, 22));
        le_prenom = new QLineEdit(groupBox);
        le_prenom->setObjectName(QStringLiteral("le_prenom"));
        le_prenom->setGeometry(QRect(160, 90, 113, 22));
        le_numero_de_cin = new QLineEdit(groupBox);
        le_numero_de_cin->setObjectName(QStringLiteral("le_numero_de_cin"));
        le_numero_de_cin->setGeometry(QRect(160, 120, 113, 22));
        le_adresse_email = new QLineEdit(groupBox);
        le_adresse_email->setObjectName(QStringLiteral("le_adresse_email"));
        le_adresse_email->setGeometry(QRect(160, 210, 113, 22));
        le_numero_de_telephone = new QLineEdit(groupBox);
        le_numero_de_telephone->setObjectName(QStringLiteral("le_numero_de_telephone"));
        le_numero_de_telephone->setGeometry(QRect(160, 240, 113, 22));
        pushButton = new QPushButton(groupBox);
        pushButton->setObjectName(QStringLiteral("pushButton"));
        pushButton->setGeometry(QRect(300, 150, 93, 28));
        label_9 = new QLabel(groupBox);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(20, 180, 31, 16));
        le_sexe = new QLineEdit(groupBox);
        le_sexe->setObjectName(QStringLiteral("le_sexe"));
        le_sexe->setGeometry(QRect(160, 180, 113, 22));
        label_nomControl = new QLabel(groupBox);
        label_nomControl->setObjectName(QStringLiteral("label_nomControl"));
        label_nomControl->setGeometry(QRect(270, 60, 31, 21));
        label_prenomControl = new QLabel(groupBox);
        label_prenomControl->setObjectName(QStringLiteral("label_prenomControl"));
        label_prenomControl->setGeometry(QRect(270, 90, 31, 21));
        label_cinControl = new QLabel(groupBox);
        label_cinControl->setObjectName(QStringLiteral("label_cinControl"));
        label_cinControl->setGeometry(QRect(270, 120, 31, 21));
        label_dateControl = new QLabel(groupBox);
        label_dateControl->setObjectName(QStringLiteral("label_dateControl"));
        label_dateControl->setGeometry(QRect(280, 150, 31, 21));
        label_sexeControl = new QLabel(groupBox);
        label_sexeControl->setObjectName(QStringLiteral("label_sexeControl"));
        label_sexeControl->setGeometry(QRect(270, 180, 31, 21));
        label_adresse_emailControl = new QLabel(groupBox);
        label_adresse_emailControl->setObjectName(QStringLiteral("label_adresse_emailControl"));
        label_adresse_emailControl->setGeometry(QRect(270, 210, 31, 21));
        label_telephoneControl = new QLabel(groupBox);
        label_telephoneControl->setObjectName(QStringLiteral("label_telephoneControl"));
        label_telephoneControl->setGeometry(QRect(270, 240, 31, 21));
        label_matriculeControl = new QLabel(groupBox);
        label_matriculeControl->setObjectName(QStringLiteral("label_matriculeControl"));
        label_matriculeControl->setGeometry(QRect(270, 30, 31, 21));
        lineEditpass = new QLineEdit(groupBox);
        lineEditpass->setObjectName(QStringLiteral("lineEditpass"));
        lineEditpass->setGeometry(QRect(160, 270, 113, 22));
        label_pass = new QLabel(groupBox);
        label_pass->setObjectName(QStringLiteral("label_pass"));
        label_pass->setGeometry(QRect(20, 270, 56, 16));
        label_21 = new QLabel(groupBox);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(270, 270, 20, 20));
        le_date_de_naissance = new QDateEdit(groupBox);
        le_date_de_naissance->setObjectName(QStringLiteral("le_date_de_naissance"));
        le_date_de_naissance->setGeometry(QRect(160, 150, 110, 22));
        label_20 = new QLabel(groupBox);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(20, 310, 56, 16));
        date = new QDateEdit(groupBox);
        date->setObjectName(QStringLiteral("date"));
        date->setGeometry(QRect(160, 300, 110, 22));
        pushButton_qu = new QPushButton(tab);
        pushButton_qu->setObjectName(QStringLiteral("pushButton_qu"));
        pushButton_qu->setGeometry(QRect(20, 40, 93, 28));
        tabWidget->addTab(tab, QString());
        tab_2 = new QWidget();
        tab_2->setObjectName(QStringLiteral("tab_2"));
        tab_employe = new QTableView(tab_2);
        tab_employe->setObjectName(QStringLiteral("tab_employe"));
        tab_employe->setGeometry(QRect(20, 110, 721, 261));
        lineEdit_rechercher = new QLineEdit(tab_2);
        lineEdit_rechercher->setObjectName(QStringLiteral("lineEdit_rechercher"));
        lineEdit_rechercher->setGeometry(QRect(20, 90, 141, 22));
        comboBoxTri = new QComboBox(tab_2);
        comboBoxTri->setObjectName(QStringLiteral("comboBoxTri"));
        comboBoxTri->setGeometry(QRect(650, 20, 111, 22));
        checkBox = new QCheckBox(tab_2);
        checkBox->setObjectName(QStringLiteral("checkBox"));
        checkBox->setGeometry(QRect(50, 380, 131, 20));
        checkBox_2 = new QCheckBox(tab_2);
        checkBox_2->setObjectName(QStringLiteral("checkBox_2"));
        checkBox_2->setGeometry(QRect(50, 410, 161, 20));
        pushButton_3 = new QPushButton(tab_2);
        pushButton_3->setObjectName(QStringLiteral("pushButton_3"));
        pushButton_3->setGeometry(QRect(410, 380, 93, 28));
        pushButton_7 = new QPushButton(tab_2);
        pushButton_7->setObjectName(QStringLiteral("pushButton_7"));
        pushButton_7->setGeometry(QRect(530, 380, 93, 28));
        pushButton_8 = new QPushButton(tab_2);
        pushButton_8->setObjectName(QStringLiteral("pushButton_8"));
        pushButton_8->setGeometry(QRect(650, 380, 93, 28));
        label_45 = new QLabel(tab_2);
        label_45->setObjectName(QStringLiteral("label_45"));
        label_45->setGeometry(QRect(0, 0, 781, 451));
        label_45->setStyleSheet(QStringLiteral("border-image: url(:/images/p0.png);"));
        pushButton_arduino = new QPushButton(tab_2);
        pushButton_arduino->setObjectName(QStringLiteral("pushButton_arduino"));
        pushButton_arduino->setGeometry(QRect(310, 380, 93, 28));
        tabWidget->addTab(tab_2, QString());
        label_45->raise();
        tab_employe->raise();
        lineEdit_rechercher->raise();
        comboBoxTri->raise();
        checkBox->raise();
        checkBox_2->raise();
        pushButton_3->raise();
        pushButton_7->raise();
        pushButton_8->raise();
        pushButton_arduino->raise();
        tab_3 = new QWidget();
        tab_3->setObjectName(QStringLiteral("tab_3"));
        lespp = new QLineEdit(tab_3);
        lespp->setObjectName(QStringLiteral("lespp"));
        lespp->setGeometry(QRect(340, 210, 113, 22));
        label_10 = new QLabel(tab_3);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(240, 210, 56, 16));
        pb_supprimer = new QPushButton(tab_3);
        pb_supprimer->setObjectName(QStringLiteral("pb_supprimer"));
        pb_supprimer->setGeometry(QRect(280, 270, 93, 28));
        label_suppControl = new QLabel(tab_3);
        label_suppControl->setObjectName(QStringLiteral("label_suppControl"));
        label_suppControl->setGeometry(QRect(480, 170, 31, 16));
        label_46 = new QLabel(tab_3);
        label_46->setObjectName(QStringLiteral("label_46"));
        label_46->setGeometry(QRect(5, 5, 781, 441));
        label_46->setStyleSheet(QStringLiteral("border-image: url(:/images/p0.png);"));
        tabWidget->addTab(tab_3, QString());
        label_46->raise();
        lespp->raise();
        label_10->raise();
        pb_supprimer->raise();
        label_suppControl->raise();
        tab_4 = new QWidget();
        tab_4->setObjectName(QStringLiteral("tab_4"));
        groupBox_2 = new QGroupBox(tab_4);
        groupBox_2->setObjectName(QStringLiteral("groupBox_2"));
        groupBox_2->setGeometry(QRect(90, 60, 561, 321));
        label_11 = new QLabel(groupBox_2);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(30, 20, 56, 16));
        label_12 = new QLabel(groupBox_2);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(30, 50, 56, 16));
        label_13 = new QLabel(groupBox_2);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(30, 80, 56, 16));
        label_14 = new QLabel(groupBox_2);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(30, 110, 111, 16));
        label_15 = new QLabel(groupBox_2);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(30, 140, 111, 16));
        label_16 = new QLabel(groupBox_2);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(30, 200, 101, 16));
        label_17 = new QLabel(groupBox_2);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(30, 230, 131, 16));
        le_matricule_2 = new QLineEdit(groupBox_2);
        le_matricule_2->setObjectName(QStringLiteral("le_matricule_2"));
        le_matricule_2->setGeometry(QRect(160, 10, 113, 22));
        le_nom_2 = new QLineEdit(groupBox_2);
        le_nom_2->setObjectName(QStringLiteral("le_nom_2"));
        le_nom_2->setGeometry(QRect(160, 40, 113, 22));
        le_prenom_2 = new QLineEdit(groupBox_2);
        le_prenom_2->setObjectName(QStringLiteral("le_prenom_2"));
        le_prenom_2->setGeometry(QRect(160, 70, 113, 22));
        le_numero_de_cin_2 = new QLineEdit(groupBox_2);
        le_numero_de_cin_2->setObjectName(QStringLiteral("le_numero_de_cin_2"));
        le_numero_de_cin_2->setGeometry(QRect(160, 100, 113, 22));
        le_adresse_email_2 = new QLineEdit(groupBox_2);
        le_adresse_email_2->setObjectName(QStringLiteral("le_adresse_email_2"));
        le_adresse_email_2->setGeometry(QRect(160, 190, 113, 22));
        le_numero_de_telephone_2 = new QLineEdit(groupBox_2);
        le_numero_de_telephone_2->setObjectName(QStringLiteral("le_numero_de_telephone_2"));
        le_numero_de_telephone_2->setGeometry(QRect(160, 220, 113, 22));
        pushButton_2 = new QPushButton(groupBox_2);
        pushButton_2->setObjectName(QStringLiteral("pushButton_2"));
        pushButton_2->setGeometry(QRect(380, 240, 93, 28));
        label_18 = new QLabel(groupBox_2);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(30, 170, 56, 16));
        le_sexe_2 = new QLineEdit(groupBox_2);
        le_sexe_2->setObjectName(QStringLiteral("le_sexe_2"));
        le_sexe_2->setGeometry(QRect(160, 160, 113, 22));
        comboBox = new QComboBox(groupBox_2);
        comboBox->setObjectName(QStringLiteral("comboBox"));
        comboBox->setGeometry(QRect(390, 60, 73, 22));
        label_matriculeControl2 = new QLabel(groupBox_2);
        label_matriculeControl2->setObjectName(QStringLiteral("label_matriculeControl2"));
        label_matriculeControl2->setGeometry(QRect(280, 10, 31, 16));
        label_nomControl2 = new QLabel(groupBox_2);
        label_nomControl2->setObjectName(QStringLiteral("label_nomControl2"));
        label_nomControl2->setGeometry(QRect(270, 40, 31, 16));
        label_prenomControl2 = new QLabel(groupBox_2);
        label_prenomControl2->setObjectName(QStringLiteral("label_prenomControl2"));
        label_prenomControl2->setGeometry(QRect(280, 70, 31, 16));
        label_cinControl2 = new QLabel(groupBox_2);
        label_cinControl2->setObjectName(QStringLiteral("label_cinControl2"));
        label_cinControl2->setGeometry(QRect(270, 100, 31, 20));
        label_dateControl2 = new QLabel(groupBox_2);
        label_dateControl2->setObjectName(QStringLiteral("label_dateControl2"));
        label_dateControl2->setGeometry(QRect(280, 280, 31, 16));
        label_sexeControl2 = new QLabel(groupBox_2);
        label_sexeControl2->setObjectName(QStringLiteral("label_sexeControl2"));
        label_sexeControl2->setGeometry(QRect(270, 160, 31, 16));
        label_adresse_emailControl2 = new QLabel(groupBox_2);
        label_adresse_emailControl2->setObjectName(QStringLiteral("label_adresse_emailControl2"));
        label_adresse_emailControl2->setGeometry(QRect(280, 190, 31, 21));
        label_telephoneControl2 = new QLabel(groupBox_2);
        label_telephoneControl2->setObjectName(QStringLiteral("label_telephoneControl2"));
        label_telephoneControl2->setGeometry(QRect(270, 220, 31, 20));
        label_20pass2 = new QLabel(groupBox_2);
        label_20pass2->setObjectName(QStringLiteral("label_20pass2"));
        label_20pass2->setGeometry(QRect(30, 260, 56, 16));
        lineEditpass2 = new QLineEdit(groupBox_2);
        lineEditpass2->setObjectName(QStringLiteral("lineEditpass2"));
        lineEditpass2->setGeometry(QRect(160, 250, 113, 22));
        label_202 = new QLabel(groupBox_2);
        label_202->setObjectName(QStringLiteral("label_202"));
        label_202->setGeometry(QRect(330, 340, 41, 16));
        le_date_de_naissance_2 = new QDateEdit(groupBox_2);
        le_date_de_naissance_2->setObjectName(QStringLiteral("le_date_de_naissance_2"));
        le_date_de_naissance_2->setGeometry(QRect(160, 130, 110, 22));
        date1 = new QLabel(groupBox_2);
        date1->setObjectName(QStringLiteral("date1"));
        date1->setGeometry(QRect(30, 290, 56, 16));
        dateEdit = new QDateEdit(groupBox_2);
        dateEdit->setObjectName(QStringLiteral("dateEdit"));
        dateEdit->setGeometry(QRect(160, 280, 110, 22));
        label_47 = new QLabel(tab_4);
        label_47->setObjectName(QStringLiteral("label_47"));
        label_47->setGeometry(QRect(0, 0, 781, 451));
        label_47->setStyleSheet(QStringLiteral("border-image: url(:/images/p0.png);"));
        tabWidget->addTab(tab_4, QString());
        label_47->raise();
        groupBox_2->raise();
        tab_5 = new QWidget();
        tab_5->setObjectName(QStringLiteral("tab_5"));
        horizontalFrame = new QFrame(tab_5);
        horizontalFrame->setObjectName(QStringLiteral("horizontalFrame"));
        horizontalFrame->setGeometry(QRect(10, 10, 751, 371));
        horizontalLayout = new QHBoxLayout(horizontalFrame);
        horizontalLayout->setObjectName(QStringLiteral("horizontalLayout"));
        pushButton_16 = new QPushButton(tab_5);
        pushButton_16->setObjectName(QStringLiteral("pushButton_16"));
        pushButton_16->setGeometry(QRect(650, 400, 93, 28));
        label_53 = new QLabel(tab_5);
        label_53->setObjectName(QStringLiteral("label_53"));
        label_53->setGeometry(QRect(0, 5, 781, 441));
        label_53->setStyleSheet(QStringLiteral("border-image: url(:/images/p0.png);"));
        tabWidget->addTab(tab_5, QString());
        label_53->raise();
        horizontalFrame->raise();
        pushButton_16->raise();
        tab_6 = new QWidget();
        tab_6->setObjectName(QStringLiteral("tab_6"));
        calendarWidget = new QCalendarWidget(tab_6);
        calendarWidget->setObjectName(QStringLiteral("calendarWidget"));
        calendarWidget->setGeometry(QRect(170, 50, 481, 351));
        label_52 = new QLabel(tab_6);
        label_52->setObjectName(QStringLiteral("label_52"));
        label_52->setGeometry(QRect(10, 0, 771, 431));
        label_52->setStyleSheet(QStringLiteral("border-image: url(:/images/p0.png);"));
        tabWidget->addTab(tab_6, QString());
        label_52->raise();
        calendarWidget->raise();
        stackedWidget->addWidget(page);
        page_5 = new QWidget();
        page_5->setObjectName(QStringLiteral("page_5"));
        tabWidget_3 = new QTabWidget(page_5);
        tabWidget_3->setObjectName(QStringLiteral("tabWidget_3"));
        tabWidget_3->setGeometry(QRect(40, 10, 881, 521));
        QFont font;
        font.setPointSize(9);
        font.setBold(true);
        font.setWeight(75);
        tabWidget_3->setFont(font);
        tab_13 = new QWidget();
        tab_13->setObjectName(QStringLiteral("tab_13"));
        groupBox_6 = new QGroupBox(tab_13);
        groupBox_6->setObjectName(QStringLiteral("groupBox_6"));
        groupBox_6->setGeometry(QRect(20, 20, 571, 431));
        label_56 = new QLabel(groupBox_6);
        label_56->setObjectName(QStringLiteral("label_56"));
        label_56->setGeometry(QRect(10, 30, 81, 21));
        QFont font1;
        font1.setPointSize(10);
        font1.setBold(true);
        font1.setWeight(75);
        label_56->setFont(font1);
        le_marque = new QLineEdit(groupBox_6);
        le_marque->setObjectName(QStringLiteral("le_marque"));
        le_marque->setGeometry(QRect(390, 30, 113, 22));
        label_57 = new QLabel(groupBox_6);
        label_57->setObjectName(QStringLiteral("label_57"));
        label_57->setGeometry(QRect(10, 80, 71, 16));
        label_57->setFont(font1);
        le_modele = new QLineEdit(groupBox_6);
        le_modele->setObjectName(QStringLiteral("le_modele"));
        le_modele->setGeometry(QRect(390, 70, 113, 22));
        label_59 = new QLabel(groupBox_6);
        label_59->setObjectName(QStringLiteral("label_59"));
        label_59->setGeometry(QRect(10, 120, 201, 21));
        label_59->setFont(font1);
        le_afb = new QLineEdit(groupBox_6);
        le_afb->setObjectName(QStringLiteral("le_afb"));
        le_afb->setGeometry(QRect(390, 120, 113, 22));
        label_58 = new QLabel(groupBox_6);
        label_58->setObjectName(QStringLiteral("label_58"));
        label_58->setGeometry(QRect(10, 160, 91, 31));
        label_58->setFont(font1);
        le_plaque_dimmat = new QLineEdit(groupBox_6);
        le_plaque_dimmat->setObjectName(QStringLiteral("le_plaque_dimmat"));
        le_plaque_dimmat->setGeometry(QRect(390, 160, 113, 22));
        label_60 = new QLabel(groupBox_6);
        label_60->setObjectName(QStringLiteral("label_60"));
        label_60->setGeometry(QRect(10, 210, 131, 31));
        label_60->setFont(font1);
        le_kilometrage = new QLineEdit(groupBox_6);
        le_kilometrage->setObjectName(QStringLiteral("le_kilometrage"));
        le_kilometrage->setGeometry(QRect(390, 210, 113, 22));
        label_61 = new QLabel(groupBox_6);
        label_61->setObjectName(QStringLiteral("label_61"));
        label_61->setGeometry(QRect(10, 320, 61, 31));
        label_61->setFont(font1);
        le_etat = new QLineEdit(groupBox_6);
        le_etat->setObjectName(QStringLiteral("le_etat"));
        le_etat->setGeometry(QRect(390, 320, 113, 22));
        label_62 = new QLabel(groupBox_6);
        label_62->setObjectName(QStringLiteral("label_62"));
        label_62->setGeometry(QRect(10, 270, 161, 31));
        label_62->setFont(font1);
        le_tarifs = new QLineEdit(groupBox_6);
        le_tarifs->setObjectName(QStringLiteral("le_tarifs"));
        le_tarifs->setGeometry(QRect(390, 270, 113, 22));
        ajouter_vo = new QPushButton(groupBox_6);
        ajouter_vo->setObjectName(QStringLiteral("ajouter_vo"));
        ajouter_vo->setGeometry(QRect(60, 370, 171, 41));
        modifier_2 = new QPushButton(groupBox_6);
        modifier_2->setObjectName(QStringLiteral("modifier_2"));
        modifier_2->setGeometry(QRect(250, 370, 171, 41));
        stat_sarah = new QPushButton(tab_13);
        stat_sarah->setObjectName(QStringLiteral("stat_sarah"));
        stat_sarah->setGeometry(QRect(640, 40, 191, 61));
        pdf_sara = new QPushButton(tab_13);
        pdf_sara->setObjectName(QStringLiteral("pdf_sara"));
        pdf_sara->setGeometry(QRect(640, 110, 191, 61));
        qrcode = new QPushButton(tab_13);
        qrcode->setObjectName(QStringLiteral("qrcode"));
        qrcode->setGeometry(QRect(640, 180, 191, 61));
        groupBox_9 = new QGroupBox(tab_13);
        groupBox_9->setObjectName(QStringLiteral("groupBox_9"));
        groupBox_9->setGeometry(QRect(600, 250, 271, 191));
        dateTimeEditConfig = new QLineEdit(groupBox_9);
        dateTimeEditConfig->setObjectName(QStringLiteral("dateTimeEditConfig"));
        dateTimeEditConfig->setGeometry(QRect(50, 50, 151, 31));
        OK = new QPushButton(groupBox_9);
        OK->setObjectName(QStringLiteral("OK"));
        OK->setGeometry(QRect(20, 130, 93, 28));
        pushButton_20 = new QPushButton(groupBox_9);
        pushButton_20->setObjectName(QStringLiteral("pushButton_20"));
        pushButton_20->setGeometry(QRect(150, 130, 93, 28));
        tabWidget_3->addTab(tab_13, QString());
        tab_14 = new QWidget();
        tab_14->setObjectName(QStringLiteral("tab_14"));
        affichertab = new QTableView(tab_14);
        affichertab->setObjectName(QStringLiteral("affichertab"));
        affichertab->setGeometry(QRect(10, 100, 831, 351));
        label_63 = new QLabel(tab_14);
        label_63->setObjectName(QStringLiteral("label_63"));
        label_63->setGeometry(QRect(30, 40, 71, 31));
        QFont font2;
        font2.setPointSize(11);
        label_63->setFont(font2);
        cherche = new QLineEdit(tab_14);
        cherche->setObjectName(QStringLiteral("cherche"));
        cherche->setGeometry(QRect(80, 40, 111, 31));
        chercher_sara = new QPushButton(tab_14);
        chercher_sara->setObjectName(QStringLiteral("chercher_sara"));
        chercher_sara->setGeometry(QRect(210, 40, 141, 31));
        pushButton_trianne = new QPushButton(tab_14);
        pushButton_trianne->setObjectName(QStringLiteral("pushButton_trianne"));
        pushButton_trianne->setGeometry(QRect(1120, 50, 111, 28));
        tarifs = new QPushButton(tab_14);
        tarifs->setObjectName(QStringLiteral("tarifs"));
        tarifs->setGeometry(QRect(670, 30, 191, 28));
        tab_tri = new QTableView(tab_14);
        tab_tri->setObjectName(QStringLiteral("tab_tri"));
        tab_tri->setGeometry(QRect(20, 660, 911, 171));
        pushButton_trianne_2 = new QPushButton(tab_14);
        pushButton_trianne_2->setObjectName(QStringLiteral("pushButton_trianne_2"));
        pushButton_trianne_2->setGeometry(QRect(670, 60, 191, 28));
        tabWidget_3->addTab(tab_14, QString());
        tab_15 = new QWidget();
        tab_15->setObjectName(QStringLiteral("tab_15"));
        groupBox_7 = new QGroupBox(tab_15);
        groupBox_7->setObjectName(QStringLiteral("groupBox_7"));
        groupBox_7->setGeometry(QRect(30, 30, 421, 441));
        label_64 = new QLabel(groupBox_7);
        label_64->setObjectName(QStringLiteral("label_64"));
        label_64->setGeometry(QRect(110, 90, 231, 31));
        QFont font3;
        font3.setFamily(QStringLiteral("Yu Gothic UI"));
        font3.setPointSize(11);
        label_64->setFont(font3);
        lineEdit_8 = new QLineEdit(groupBox_7);
        lineEdit_8->setObjectName(QStringLiteral("lineEdit_8"));
        lineEdit_8->setGeometry(QRect(130, 150, 181, 41));
        supp_sara = new QPushButton(groupBox_7);
        supp_sara->setObjectName(QStringLiteral("supp_sara"));
        supp_sara->setGeometry(QRect(130, 230, 181, 61));
        tabWidget_3->addTab(tab_15, QString());
        tab_18 = new QWidget();
        tab_18->setObjectName(QStringLiteral("tab_18"));
        groupBox_8 = new QGroupBox(tab_18);
        groupBox_8->setObjectName(QStringLiteral("groupBox_8"));
        groupBox_8->setGeometry(QRect(70, 50, 441, 421));
        label_72 = new QLabel(groupBox_8);
        label_72->setObjectName(QStringLiteral("label_72"));
        label_72->setGeometry(QRect(90, 60, 261, 21));
        QFont font4;
        font4.setFamily(QStringLiteral("Yu Gothic UI"));
        font4.setPointSize(11);
        font4.setItalic(false);
        label_72->setFont(font4);
        label_72->setFocusPolicy(Qt::StrongFocus);
        label_72->setLineWidth(2);
        label_72->setScaledContents(true);
        label_72->setWordWrap(true);
        lineEditPlaqueImmatriculation = new QLineEdit(groupBox_8);
        lineEditPlaqueImmatriculation->setObjectName(QStringLiteral("lineEditPlaqueImmatriculation"));
        lineEditPlaqueImmatriculation->setGeometry(QRect(90, 140, 201, 31));
        aff = new QLabel(groupBox_8);
        aff->setObjectName(QStringLiteral("aff"));
        aff->setGeometry(QRect(40, 250, 341, 131));
        kilometrage = new QPushButton(groupBox_8);
        kilometrage->setObjectName(QStringLiteral("kilometrage"));
        kilometrage->setGeometry(QRect(110, 220, 161, 41));
        tabWidget_3->addTab(tab_18, QString());
        pushButton_22 = new QPushButton(page_5);
        pushButton_22->setObjectName(QStringLiteral("pushButton_22"));
        pushButton_22->setGeometry(QRect(930, 30, 61, 51));
        stackedWidget->addWidget(page_5);
        page_4 = new QWidget();
        page_4->setObjectName(QStringLiteral("page_4"));
        tabWidget_2 = new QTabWidget(page_4);
        tabWidget_2->setObjectName(QStringLiteral("tabWidget_2"));
        tabWidget_2->setGeometry(QRect(50, 40, 871, 471));
        tab_7 = new QWidget();
        tab_7->setObjectName(QStringLiteral("tab_7"));
        groupBox_4 = new QGroupBox(tab_7);
        groupBox_4->setObjectName(QStringLiteral("groupBox_4"));
        groupBox_4->setGeometry(QRect(200, 80, 441, 291));
        label_22 = new QLabel(groupBox_4);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(70, 20, 56, 16));
        label_23 = new QLabel(groupBox_4);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(70, 50, 56, 16));
        label_24 = new QLabel(groupBox_4);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(70, 90, 56, 16));
        label_25 = new QLabel(groupBox_4);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(70, 130, 91, 16));
        label_26 = new QLabel(groupBox_4);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(70, 160, 71, 16));
        label_27 = new QLabel(groupBox_4);
        label_27->setObjectName(QStringLiteral("label_27"));
        label_27->setGeometry(QRect(70, 200, 56, 16));
        label_28 = new QLabel(groupBox_4);
        label_28->setObjectName(QStringLiteral("label_28"));
        label_28->setGeometry(QRect(70, 230, 56, 16));
        label_29 = new QLabel(groupBox_4);
        label_29->setObjectName(QStringLiteral("label_29"));
        label_29->setGeometry(QRect(70, 260, 56, 16));
        lineEdit_NOM = new QLineEdit(groupBox_4);
        lineEdit_NOM->setObjectName(QStringLiteral("lineEdit_NOM"));
        lineEdit_NOM->setGeometry(QRect(180, 20, 113, 22));
        lineEdit_PRENOM = new QLineEdit(groupBox_4);
        lineEdit_PRENOM->setObjectName(QStringLiteral("lineEdit_PRENOM"));
        lineEdit_PRENOM->setGeometry(QRect(180, 50, 113, 22));
        lineEdit_ADRESSE = new QLineEdit(groupBox_4);
        lineEdit_ADRESSE->setObjectName(QStringLiteral("lineEdit_ADRESSE"));
        lineEdit_ADRESSE->setGeometry(QRect(180, 90, 113, 22));
        lineEdit_ADRESSEEMAIL = new QLineEdit(groupBox_4);
        lineEdit_ADRESSEEMAIL->setObjectName(QStringLiteral("lineEdit_ADRESSEEMAIL"));
        lineEdit_ADRESSEEMAIL->setGeometry(QRect(180, 130, 113, 22));
        lineEdit_NUMPERMIS = new QLineEdit(groupBox_4);
        lineEdit_NUMPERMIS->setObjectName(QStringLiteral("lineEdit_NUMPERMIS"));
        lineEdit_NUMPERMIS->setGeometry(QRect(180, 160, 113, 22));
        lineEdit_NUMTEL = new QLineEdit(groupBox_4);
        lineEdit_NUMTEL->setObjectName(QStringLiteral("lineEdit_NUMTEL"));
        lineEdit_NUMTEL->setGeometry(QRect(180, 220, 113, 22));
        lineEdit_NUMCIN = new QLineEdit(groupBox_4);
        lineEdit_NUMCIN->setObjectName(QStringLiteral("lineEdit_NUMCIN"));
        lineEdit_NUMCIN->setGeometry(QRect(180, 260, 113, 22));
        pushButton_10 = new QPushButton(groupBox_4);
        pushButton_10->setObjectName(QStringLiteral("pushButton_10"));
        pushButton_10->setGeometry(QRect(340, 250, 93, 28));
        lineEdit_NAISSANCE = new QDateEdit(groupBox_4);
        lineEdit_NAISSANCE->setObjectName(QStringLiteral("lineEdit_NAISSANCE"));
        lineEdit_NAISSANCE->setGeometry(QRect(180, 190, 110, 22));
        label_48 = new QLabel(tab_7);
        label_48->setObjectName(QStringLiteral("label_48"));
        label_48->setGeometry(QRect(0, 0, 871, 441));
        label_48->setStyleSheet(QStringLiteral("border-image: url(:/images/p0.png);"));
        pushButton_17 = new QPushButton(tab_7);
        pushButton_17->setObjectName(QStringLiteral("pushButton_17"));
        pushButton_17->setGeometry(QRect(30, 40, 93, 28));
        tabWidget_2->addTab(tab_7, QString());
        label_48->raise();
        groupBox_4->raise();
        pushButton_17->raise();
        tab_8 = new QWidget();
        tab_8->setObjectName(QStringLiteral("tab_8"));
        tableView = new QTableView(tab_8);
        tableView->setObjectName(QStringLiteral("tableView"));
        tableView->setGeometry(QRect(40, 20, 771, 161));
        tableView_2 = new QTableView(tab_8);
        tableView_2->setObjectName(QStringLiteral("tableView_2"));
        tableView_2->setGeometry(QRect(45, 260, 761, 131));
        pushButton_11 = new QPushButton(tab_8);
        pushButton_11->setObjectName(QStringLiteral("pushButton_11"));
        pushButton_11->setGeometry(QRect(420, 200, 93, 28));
        pushButton_12 = new QPushButton(tab_8);
        pushButton_12->setObjectName(QStringLiteral("pushButton_12"));
        pushButton_12->setGeometry(QRect(530, 200, 93, 28));
        pushButton_13 = new QPushButton(tab_8);
        pushButton_13->setObjectName(QStringLiteral("pushButton_13"));
        pushButton_13->setGeometry(QRect(650, 200, 93, 28));
        rechercher = new QLineEdit(tab_8);
        rechercher->setObjectName(QStringLiteral("rechercher"));
        rechercher->setGeometry(QRect(130, 200, 113, 22));
        label_49 = new QLabel(tab_8);
        label_49->setObjectName(QStringLiteral("label_49"));
        label_49->setGeometry(QRect(0, 0, 861, 441));
        label_49->setStyleSheet(QStringLiteral("border-image: url(:/images/p0.png);"));
        tabWidget_2->addTab(tab_8, QString());
        label_49->raise();
        tableView->raise();
        tableView_2->raise();
        pushButton_11->raise();
        pushButton_12->raise();
        pushButton_13->raise();
        rechercher->raise();
        tab_9 = new QWidget();
        tab_9->setObjectName(QStringLiteral("tab_9"));
        lineEdit_2 = new QLineEdit(tab_9);
        lineEdit_2->setObjectName(QStringLiteral("lineEdit_2"));
        lineEdit_2->setGeometry(QRect(280, 160, 113, 22));
        label_30 = new QLabel(tab_9);
        label_30->setObjectName(QStringLiteral("label_30"));
        label_30->setGeometry(QRect(140, 160, 56, 16));
        pushButton_14 = new QPushButton(tab_9);
        pushButton_14->setObjectName(QStringLiteral("pushButton_14"));
        pushButton_14->setGeometry(QRect(240, 220, 93, 28));
        label_50 = new QLabel(tab_9);
        label_50->setObjectName(QStringLiteral("label_50"));
        label_50->setGeometry(QRect(0, 0, 861, 451));
        label_50->setStyleSheet(QStringLiteral("border-image: url(:/images/p0.png);"));
        tabWidget_2->addTab(tab_9, QString());
        label_50->raise();
        lineEdit_2->raise();
        label_30->raise();
        pushButton_14->raise();
        tab_10 = new QWidget();
        tab_10->setObjectName(QStringLiteral("tab_10"));
        groupBox_5 = new QGroupBox(tab_10);
        groupBox_5->setObjectName(QStringLiteral("groupBox_5"));
        groupBox_5->setGeometry(QRect(210, 50, 381, 301));
        lineEdit_nom = new QLineEdit(groupBox_5);
        lineEdit_nom->setObjectName(QStringLiteral("lineEdit_nom"));
        lineEdit_nom->setGeometry(QRect(150, 20, 113, 22));
        lineEdit_prenom = new QLineEdit(groupBox_5);
        lineEdit_prenom->setObjectName(QStringLiteral("lineEdit_prenom"));
        lineEdit_prenom->setGeometry(QRect(150, 50, 113, 22));
        lineEdit_numpermis = new QLineEdit(groupBox_5);
        lineEdit_numpermis->setObjectName(QStringLiteral("lineEdit_numpermis"));
        lineEdit_numpermis->setGeometry(QRect(150, 140, 113, 22));
        lineEdit_adresse = new QLineEdit(groupBox_5);
        lineEdit_adresse->setObjectName(QStringLiteral("lineEdit_adresse"));
        lineEdit_adresse->setGeometry(QRect(150, 80, 113, 22));
        lineEdit_email = new QLineEdit(groupBox_5);
        lineEdit_email->setObjectName(QStringLiteral("lineEdit_email"));
        lineEdit_email->setGeometry(QRect(150, 110, 113, 22));
        lineEdit_numtel = new QLineEdit(groupBox_5);
        lineEdit_numtel->setObjectName(QStringLiteral("lineEdit_numtel"));
        lineEdit_numtel->setGeometry(QRect(150, 210, 113, 22));
        cinToModifyLineEdit = new QLineEdit(groupBox_5);
        cinToModifyLineEdit->setObjectName(QStringLiteral("cinToModifyLineEdit"));
        cinToModifyLineEdit->setGeometry(QRect(150, 240, 113, 22));
        pushButton_15 = new QPushButton(groupBox_5);
        pushButton_15->setObjectName(QStringLiteral("pushButton_15"));
        pushButton_15->setGeometry(QRect(280, 160, 93, 28));
        label_31 = new QLabel(groupBox_5);
        label_31->setObjectName(QStringLiteral("label_31"));
        label_31->setGeometry(QRect(60, 20, 56, 16));
        label_32 = new QLabel(groupBox_5);
        label_32->setObjectName(QStringLiteral("label_32"));
        label_32->setGeometry(QRect(60, 50, 56, 16));
        label_33 = new QLabel(groupBox_5);
        label_33->setObjectName(QStringLiteral("label_33"));
        label_33->setGeometry(QRect(60, 80, 56, 16));
        label_34 = new QLabel(groupBox_5);
        label_34->setObjectName(QStringLiteral("label_34"));
        label_34->setGeometry(QRect(60, 110, 91, 16));
        label_35 = new QLabel(groupBox_5);
        label_35->setObjectName(QStringLiteral("label_35"));
        label_35->setGeometry(QRect(60, 140, 81, 16));
        label_36 = new QLabel(groupBox_5);
        label_36->setObjectName(QStringLiteral("label_36"));
        label_36->setGeometry(QRect(60, 180, 56, 16));
        label_37 = new QLabel(groupBox_5);
        label_37->setObjectName(QStringLiteral("label_37"));
        label_37->setGeometry(QRect(60, 210, 56, 16));
        label_38 = new QLabel(groupBox_5);
        label_38->setObjectName(QStringLiteral("label_38"));
        label_38->setGeometry(QRect(60, 240, 56, 16));
        lineEdit_naissance = new QDateEdit(groupBox_5);
        lineEdit_naissance->setObjectName(QStringLiteral("lineEdit_naissance"));
        lineEdit_naissance->setGeometry(QRect(150, 180, 110, 22));
        label_51 = new QLabel(tab_10);
        label_51->setObjectName(QStringLiteral("label_51"));
        label_51->setGeometry(QRect(0, 0, 871, 441));
        label_51->setStyleSheet(QStringLiteral("border-image: url(:/images/p0.png);"));
        tabWidget_2->addTab(tab_10, QString());
        label_51->raise();
        groupBox_5->raise();
        tab_11 = new QWidget();
        tab_11->setObjectName(QStringLiteral("tab_11"));
        frame = new QFrame(tab_11);
        frame->setObjectName(QStringLiteral("frame"));
        frame->setGeometry(QRect(10, 29, 831, 361));
        tabWidget_2->addTab(tab_11, QString());
        tab_12 = new QWidget();
        tab_12->setObjectName(QStringLiteral("tab_12"));
        pushButton_19 = new QPushButton(tab_12);
        pushButton_19->setObjectName(QStringLiteral("pushButton_19"));
        pushButton_19->setGeometry(QRect(550, 320, 93, 28));
        lineEditcl = new QLineEdit(tab_12);
        lineEditcl->setObjectName(QStringLiteral("lineEditcl"));
        lineEditcl->setGeometry(QRect(310, 150, 113, 22));
        lineEdit_3 = new QLineEdit(tab_12);
        lineEdit_3->setObjectName(QStringLiteral("lineEdit_3"));
        lineEdit_3->setGeometry(QRect(320, 210, 113, 22));
        label_54 = new QLabel(tab_12);
        label_54->setObjectName(QStringLiteral("label_54"));
        label_54->setGeometry(QRect(170, 150, 121, 16));
        label_55 = new QLabel(tab_12);
        label_55->setObjectName(QStringLiteral("label_55"));
        label_55->setGeometry(QRect(200, 210, 56, 16));
        tabWidget_2->addTab(tab_12, QString());
        stackedWidget->addWidget(page_4);
        page_2 = new QWidget();
        page_2->setObjectName(QStringLiteral("page_2"));
        groupBox_3 = new QGroupBox(page_2);
        groupBox_3->setObjectName(QStringLiteral("groupBox_3"));
        groupBox_3->setGeometry(QRect(270, 190, 331, 251));
        lineEdit_username = new QLineEdit(groupBox_3);
        lineEdit_username->setObjectName(QStringLiteral("lineEdit_username"));
        lineEdit_username->setGeometry(QRect(160, 60, 113, 22));
        lineEdit_password = new QLineEdit(groupBox_3);
        lineEdit_password->setObjectName(QStringLiteral("lineEdit_password"));
        lineEdit_password->setGeometry(QRect(160, 130, 113, 22));
        label = new QLabel(groupBox_3);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(30, 60, 91, 20));
        label->setStyleSheet(QLatin1String("\n"
"font: 75 10pt \"MS Shell Dlg 2\";"));
        label_19 = new QLabel(groupBox_3);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(30, 130, 91, 21));
        label_19->setStyleSheet(QStringLiteral("font: 75 10pt \"MS Shell Dlg 2\";"));
        pushButton_5 = new QPushButton(groupBox_3);
        pushButton_5->setObjectName(QStringLiteral("pushButton_5"));
        pushButton_5->setGeometry(QRect(180, 200, 93, 28));
        pushButton_5->setStyleSheet(QStringLiteral("font: 75 10pt \"MS Shell Dlg 2\";"));
        pushButton_6 = new QPushButton(groupBox_3);
        pushButton_6->setObjectName(QStringLiteral("pushButton_6"));
        pushButton_6->setGeometry(QRect(30, 200, 93, 28));
        pushButton_6->setStyleSheet(QStringLiteral("font: 75 10pt \"MS Shell Dlg 2\";"));
        label_39 = new QLabel(page_2);
        label_39->setObjectName(QStringLiteral("label_39"));
        label_39->setGeometry(QRect(-10, 10, 941, 531));
        label_39->setStyleSheet(QStringLiteral("border-image: url(:/images/p0.png);"));
        label_40 = new QLabel(page_2);
        label_40->setObjectName(QStringLiteral("label_40"));
        label_40->setGeometry(QRect(310, 60, 251, 161));
        label_40->setStyleSheet(QStringLiteral("border-image: url(:/images/p.png);"));
        stackedWidget->addWidget(page_2);
        label_39->raise();
        groupBox_3->raise();
        label_40->raise();
        page_3 = new QWidget();
        page_3->setObjectName(QStringLiteral("page_3"));
        pushButton_4 = new QPushButton(page_3);
        pushButton_4->setObjectName(QStringLiteral("pushButton_4"));
        pushButton_4->setGeometry(QRect(40, 400, 121, 41));
        pushButton_4->setStyleSheet(QLatin1String("font: 75 14pt \"MS Shell Dlg 2\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(64, 171, 89, 255), stop:1 rgba(255, 255, 255, 255));"));
        pushButton_9 = new QPushButton(page_3);
        pushButton_9->setObjectName(QStringLiteral("pushButton_9"));
        pushButton_9->setGeometry(QRect(170, 400, 121, 41));
        pushButton_9->setToolTipDuration(0);
        pushButton_9->setStyleSheet(QLatin1String("font: 75 14pt \"MS Shell Dlg 2\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(64, 171, 89, 255), stop:1 rgba(255, 255, 255, 255));"));
        label_41 = new QLabel(page_3);
        label_41->setObjectName(QStringLiteral("label_41"));
        label_41->setGeometry(QRect(20, 0, 911, 491));
        label_41->setStyleSheet(QStringLiteral("border-image: url(:/images/p0.png);"));
        label_42 = new QLabel(page_3);
        label_42->setObjectName(QStringLiteral("label_42"));
        label_42->setGeometry(QRect(240, 80, 241, 61));
        label_42->setStyleSheet(QLatin1String("font: 48pt \"Snap ITC\";\n"
"color: rgb(0, 85, 0);"));
        label_43 = new QLabel(page_3);
        label_43->setObjectName(QStringLiteral("label_43"));
        label_43->setGeometry(QRect(610, 160, 261, 231));
        label_43->setStyleSheet(QStringLiteral("border-image: url(:/images/p.png);"));
        pushButton_18 = new QPushButton(page_3);
        pushButton_18->setObjectName(QStringLiteral("pushButton_18"));
        pushButton_18->setGeometry(QRect(780, 400, 121, 41));
        pushButton_18->setStyleSheet(QLatin1String("font: 75 14pt \"MS Shell Dlg 2\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(64, 171, 89, 255), stop:1 rgba(255, 255, 255, 255));"));
        pushButton_21 = new QPushButton(page_3);
        pushButton_21->setObjectName(QStringLiteral("pushButton_21"));
        pushButton_21->setGeometry(QRect(300, 400, 121, 41));
        pushButton_21->setStyleSheet(QLatin1String("font: 75 14pt \"MS Shell Dlg 2\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(64, 171, 89, 255), stop:1 rgba(255, 255, 255, 255));"));
        pushButton_23 = new QPushButton(page_3);
        pushButton_23->setObjectName(QStringLiteral("pushButton_23"));
        pushButton_23->setGeometry(QRect(430, 400, 121, 41));
        pushButton_23->setStyleSheet(QLatin1String("font: 75 14pt \"MS Shell Dlg 2\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(64, 171, 89, 255), stop:1 rgba(255, 255, 255, 255));"));
        stackedWidget->addWidget(page_3);
        label_41->raise();
        pushButton_4->raise();
        pushButton_9->raise();
        label_42->raise();
        label_43->raise();
        pushButton_18->raise();
        pushButton_21->raise();
        pushButton_23->raise();
        page_6 = new QWidget();
        page_6->setObjectName(QStringLiteral("page_6"));
        contrat_a = new QPushButton(page_6);
        contrat_a->setObjectName(QStringLiteral("contrat_a"));
        contrat_a->setGeometry(QRect(670, 400, 93, 28));
        groupBox_10 = new QGroupBox(page_6);
        groupBox_10->setObjectName(QStringLiteral("groupBox_10"));
        groupBox_10->setGeometry(QRect(-1, 30, 651, 291));
        QFont font5;
        font5.setFamily(QStringLiteral("Candara"));
        font5.setPointSize(28);
        font5.setBold(false);
        font5.setWeight(50);
        groupBox_10->setFont(font5);
        groupBox_10->setStyleSheet(QString::fromUtf8("background-color:rgb(179, 160,background-color: #76CCC0; /* Change the background color to green */\n"
"  border: 2px solid white;\n"
"  color: #008F8A;\n"
"\n"
"font-family: \"Roboto\", sans-serif; /* Police Roboto */\n"
"  padding: 10px 20px;\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"  display: inline-block;\n"
"  font-size: 16px;\n"
"   border-radius: 20px !important; /* Adjust this value to make the corners more rounded */\n"
"  cursor:\302\240pointer; 255);"));
        label_44 = new QLabel(groupBox_10);
        label_44->setObjectName(QStringLiteral("label_44"));
        label_44->setGeometry(QRect(50, 70, 91, 21));
        QFont font6;
        font6.setFamily(QStringLiteral("Bahnschrift"));
        font6.setPointSize(16);
        label_44->setFont(font6);
        label_44->setStyleSheet(QString::fromUtf8("background-color:rgb(170, background-color: #76CCC0; /* Change the background color to green */\n"
"  border: 2px solid white;\n"
"  color: #008F8A;\n"
"\n"
"font-family: \"Roboto\", sans-serif; /* Police Roboto */\n"
"  padding: 10px 20px;\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"  display: inline-block;\n"
"  font-size: 16px;\n"
"   border-radius: 20px !important; /* Adjust this value to make the corners more rounded */\n"
"  cursor:\302\240pointer;170, 0)"));
        label_65 = new QLabel(groupBox_10);
        label_65->setObjectName(QStringLiteral("label_65"));
        label_65->setGeometry(QRect(50, 250, 131, 21));
        label_65->setFont(font6);
        label_65->setStyleSheet(QString::fromUtf8("background-color: #76CCC0; /* Change the background color to green */\n"
"  border: 2px solid white;\n"
"  color: #008F8A;\n"
"\n"
"font-family: \"Roboto\", sans-serif; /* Police Roboto */\n"
"  padding: 10px 20px;\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"  display: inline-block;\n"
"  font-size: 16px;\n"
"   border-radius: 20px !important; /* Adjust this value to make the corners more rounded */\n"
"  cursor:\302\240pointer;"));
        label_66 = new QLabel(groupBox_10);
        label_66->setObjectName(QStringLiteral("label_66"));
        label_66->setGeometry(QRect(50, 130, 91, 21));
        label_66->setFont(font6);
        label_66->setStyleSheet(QString::fromUtf8("background-color:rgb(170, 1background-color: #76CCC0; /* Change the background color to green */\n"
"  border: 2px solid white;\n"
"  color: #008F8A;\n"
"\n"
"font-family: \"Roboto\", sans-serif; /* Police Roboto */\n"
"  padding: 10px 20px;\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"  display: inline-block;\n"
"  font-size: 16px;\n"
"   border-radius: 20px !important; /* Adjust this value to make the corners more rounded */\n"
"  cursor:\302\240pointer;70, 0)"));
        label_67 = new QLabel(groupBox_10);
        label_67->setObjectName(QStringLiteral("label_67"));
        label_67->setGeometry(QRect(50, 190, 91, 21));
        label_67->setFont(font6);
        label_67->setStyleSheet(QString::fromUtf8("background-color: #76CCC0; /* Change the background color to green */\n"
"  border: 2px solid white;\n"
"  color: #008F8A;\n"
"\n"
"font-family: \"Roboto\", sans-serif; /* Police Roboto */\n"
"  padding: 10px 20px;\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"  display: inline-block;\n"
"  font-size: 16px;\n"
"   border-radius: 20px !important; /* Adjust this value to make the corners more rounded */\n"
"  cursor:\302\240pointer;"));
        CONTRATID = new QLineEdit(groupBox_10);
        CONTRATID->setObjectName(QStringLiteral("CONTRATID"));
        CONTRATID->setGeometry(QRect(240, 70, 113, 20));
        CONTRATID->setStyleSheet(QStringLiteral("background-color:rgb(255, 255, 255)"));
        ajouter = new QPushButton(groupBox_10);
        ajouter->setObjectName(QStringLiteral("ajouter"));
        ajouter->setGeometry(QRect(550, 90, 75, 23));
        ajouter->setStyleSheet(QStringLiteral(""));
        modifier = new QPushButton(groupBox_10);
        modifier->setObjectName(QStringLiteral("modifier"));
        modifier->setGeometry(QRect(400, 90, 75, 23));
        modifier->setStyleSheet(QStringLiteral(""));
        supprimer = new QPushButton(groupBox_10);
        supprimer->setObjectName(QStringLiteral("supprimer"));
        supprimer->setGeometry(QRect(390, 200, 101, 23));
        supprimer->setStyleSheet(QStringLiteral(""));
        afficher = new QPushButton(groupBox_10);
        afficher->setObjectName(QStringLiteral("afficher"));
        afficher->setGeometry(QRect(550, 200, 75, 23));
        afficher->setStyleSheet(QStringLiteral(""));
        MONTANT = new QLineEdit(groupBox_10);
        MONTANT->setObjectName(QStringLiteral("MONTANT"));
        MONTANT->setGeometry(QRect(240, 250, 113, 20));
        MONTANT->setStyleSheet(QStringLiteral("background-color:rgb(255, 255, 255)"));
        DATEDEBUT = new QDateEdit(groupBox_10);
        DATEDEBUT->setObjectName(QStringLiteral("DATEDEBUT"));
        DATEDEBUT->setGeometry(QRect(240, 130, 110, 22));
        DATEFIN = new QDateEdit(groupBox_10);
        DATEFIN->setObjectName(QStringLiteral("DATEFIN"));
        DATEFIN->setGeometry(QRect(240, 190, 110, 22));
        pdf = new QPushButton(groupBox_10);
        pdf->setObjectName(QStringLiteral("pdf"));
        pdf->setGeometry(QRect(390, 260, 101, 23));
        pdf->setStyleSheet(QStringLiteral(""));
        stattt = new QPushButton(groupBox_10);
        stattt->setObjectName(QStringLiteral("stattt"));
        stattt->setGeometry(QRect(540, 260, 101, 23));
        stattt->setStyleSheet(QStringLiteral(""));
        tri_3 = new QPushButton(page_6);
        tri_3->setObjectName(QStringLiteral("tri_3"));
        tri_3->setGeometry(QRect(1230, 20, 20, 23));
        tri_3->setStyleSheet(QStringLiteral(""));
        chercher = new QLineEdit(page_6);
        chercher->setObjectName(QStringLiteral("chercher"));
        chercher->setGeometry(QRect(1120, 100, 113, 20));
        chercher->setStyleSheet(QStringLiteral("background-color:rgb(255, 255, 255)"));
        tableViewHistorique = new QTableView(page_6);
        tableViewHistorique->setObjectName(QStringLiteral("tableViewHistorique"));
        tableViewHistorique->setGeometry(QRect(1000, 310, 251, 151));
        tableViewHistorique->setStyleSheet(QString::fromUtf8("background-color:rgb(179, 160, 25background-color: #76CCC0; /* Change the background color to green */\n"
"  border: 2px solid white;\n"
"  color: #008F8A;\n"
"\n"
"font-family: \"Roboto\", sans-serif; /* Police Roboto */\n"
"  padding: 10px 20px;\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"  display: inline-block;\n"
"  font-size: 16px;\n"
"   border-radius: 20px !important; /* Adjust this value to make the corners more rounded */\n"
"  cursor:\302\240pointer;5);"));
        tableViewHistorique->setFrameShape(QFrame::WinPanel);
        tableViewHistorique->setFrameShadow(QFrame::Plain);
        id_ca = new QLineEdit(page_6);
        id_ca->setObjectName(QStringLiteral("id_ca"));
        id_ca->setGeometry(QRect(870, 40, 113, 20));
        id_ca->setStyleSheet(QStringLiteral("background-color:rgb(255, 255, 255)"));
        historique = new QPushButton(page_6);
        historique->setObjectName(QStringLiteral("historique"));
        historique->setGeometry(QRect(870, 340, 101, 23));
        historique->setStyleSheet(QStringLiteral(""));
        tri_2 = new QPushButton(page_6);
        tri_2->setObjectName(QStringLiteral("tri_2"));
        tri_2->setGeometry(QRect(880, 80, 101, 23));
        tri_2->setStyleSheet(QStringLiteral(""));
        affiche_tab = new QTableView(page_6);
        affiche_tab->setObjectName(QStringLiteral("affiche_tab"));
        affiche_tab->setGeometry(QRect(660, 130, 591, 151));
        affiche_tab->setStyleSheet(QString::fromUtf8("background-color:rgb(179, 160, 25background-color: #76CCC0; /* Change the background color to green */\n"
"  border: 2px solid white;\n"
"  color: #008F8A;\n"
"\n"
"font-family: \"Roboto\", sans-serif; /* Police Roboto */\n"
"  padding: 10px 20px;\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"  display: inline-block;\n"
"  font-size: 16px;\n"
"   border-radius: 20px !important; /* Adjust this value to make the corners more rounded */\n"
"  cursor:\302\240pointer;5);"));
        affiche_tab->setFrameShape(QFrame::WinPanel);
        affiche_tab->setFrameShadow(QFrame::Plain);
        tri = new QPushButton(page_6);
        tri->setObjectName(QStringLiteral("tri"));
        tri->setGeometry(QRect(660, 90, 101, 23));
        tri->setStyleSheet(QStringLiteral(""));
        label_68 = new QLabel(page_6);
        label_68->setObjectName(QStringLiteral("label_68"));
        label_68->setGeometry(QRect(0, 0, 1311, 711));
        label_68->setStyleSheet(QStringLiteral("border-image: url(:/images/p0.png);"));
        stackedWidget->addWidget(page_6);
        label_68->raise();
        contrat_a->raise();
        groupBox_10->raise();
        tri_3->raise();
        chercher->raise();
        tableViewHistorique->raise();
        id_ca->raise();
        historique->raise();
        tri_2->raise();
        affiche_tab->raise();
        tri->raise();
        interface1->setCentralWidget(centralwidget);

        retranslateUi(interface1);

        stackedWidget->setCurrentIndex(5);
        tabWidget->setCurrentIndex(4);
        tabWidget_3->setCurrentIndex(1);
        tabWidget_2->setCurrentIndex(3);


        QMetaObject::connectSlotsByName(interface1);
    } // setupUi

    void retranslateUi(QMainWindow *interface1)
    {
        interface1->setWindowTitle(QApplication::translate("interface1", "tap&go", Q_NULLPTR));
        groupBox->setTitle(QString());
        label_2->setText(QApplication::translate("interface1", "matricule", Q_NULLPTR));
        label_3->setText(QApplication::translate("interface1", "nom", Q_NULLPTR));
        label_4->setText(QApplication::translate("interface1", "prenom", Q_NULLPTR));
        label_5->setText(QApplication::translate("interface1", "numero de cin", Q_NULLPTR));
        label_6->setText(QApplication::translate("interface1", "date de naissance", Q_NULLPTR));
        label_7->setText(QApplication::translate("interface1", "adresse email", Q_NULLPTR));
        label_8->setText(QApplication::translate("interface1", "numero de talephone", Q_NULLPTR));
        pushButton->setText(QApplication::translate("interface1", "ajouter", Q_NULLPTR));
        label_9->setText(QApplication::translate("interface1", "sexe", Q_NULLPTR));
        label_nomControl->setText(QString());
        label_prenomControl->setText(QString());
        label_cinControl->setText(QString());
        label_dateControl->setText(QString());
        label_sexeControl->setText(QString());
        label_adresse_emailControl->setText(QString());
        label_telephoneControl->setText(QString());
        label_matriculeControl->setText(QString());
        label_pass->setText(QApplication::translate("interface1", "pass", Q_NULLPTR));
        label_21->setText(QString());
        label_20->setText(QApplication::translate("interface1", "date", Q_NULLPTR));
        pushButton_qu->setText(QApplication::translate("interface1", "quitter", Q_NULLPTR));
        tabWidget->setTabText(tabWidget->indexOf(tab), QApplication::translate("interface1", "ajouter", Q_NULLPTR));
        checkBox->setText(QApplication::translate("interface1", "recherche par nom", Q_NULLPTR));
        checkBox_2->setText(QApplication::translate("interface1", "recherche par matricule", Q_NULLPTR));
        pushButton_3->setText(QApplication::translate("interface1", "pdf", Q_NULLPTR));
        pushButton_7->setText(QApplication::translate("interface1", "cap", Q_NULLPTR));
        pushButton_8->setText(QApplication::translate("interface1", "excel", Q_NULLPTR));
        label_45->setText(QString());
        pushButton_arduino->setText(QApplication::translate("interface1", "arduino", Q_NULLPTR));
        tabWidget->setTabText(tabWidget->indexOf(tab_2), QApplication::translate("interface1", "afficher", Q_NULLPTR));
        label_10->setText(QApplication::translate("interface1", "matricule", Q_NULLPTR));
        pb_supprimer->setText(QApplication::translate("interface1", "supprimer", Q_NULLPTR));
        label_suppControl->setText(QString());
        label_46->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(tab_3), QApplication::translate("interface1", "supprimer", Q_NULLPTR));
        groupBox_2->setTitle(QString());
        label_11->setText(QApplication::translate("interface1", "matricule", Q_NULLPTR));
        label_12->setText(QApplication::translate("interface1", "nom", Q_NULLPTR));
        label_13->setText(QApplication::translate("interface1", "prenom", Q_NULLPTR));
        label_14->setText(QApplication::translate("interface1", "numero de cin", Q_NULLPTR));
        label_15->setText(QApplication::translate("interface1", "date de naissance", Q_NULLPTR));
        label_16->setText(QApplication::translate("interface1", "adresse email", Q_NULLPTR));
        label_17->setText(QApplication::translate("interface1", "numero de talephone", Q_NULLPTR));
        pushButton_2->setText(QApplication::translate("interface1", "modifier", Q_NULLPTR));
        label_18->setText(QApplication::translate("interface1", "sexe", Q_NULLPTR));
        label_matriculeControl2->setText(QString());
        label_nomControl2->setText(QString());
        label_prenomControl2->setText(QString());
        label_cinControl2->setText(QString());
        label_dateControl2->setText(QString());
        label_sexeControl2->setText(QString());
        label_adresse_emailControl2->setText(QString());
        label_telephoneControl2->setText(QString());
        label_20pass2->setText(QApplication::translate("interface1", "pass", Q_NULLPTR));
        label_202->setText(QString());
        date1->setText(QApplication::translate("interface1", "date", Q_NULLPTR));
        label_47->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(tab_4), QApplication::translate("interface1", "modifier", Q_NULLPTR));
        pushButton_16->setText(QApplication::translate("interface1", "capture", Q_NULLPTR));
        label_53->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(tab_5), QApplication::translate("interface1", "stat", Q_NULLPTR));
        label_52->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(tab_6), QApplication::translate("interface1", "calendrier", Q_NULLPTR));
        groupBox_6->setTitle(QApplication::translate("interface1", "ajout", Q_NULLPTR));
        label_56->setText(QApplication::translate("interface1", "marque", Q_NULLPTR));
        label_57->setText(QApplication::translate("interface1", "modele", Q_NULLPTR));
        label_59->setText(QApplication::translate("interface1", "ann\303\251e de fabrication", Q_NULLPTR));
        label_58->setText(QApplication::translate("interface1", "plaque", Q_NULLPTR));
        label_60->setText(QApplication::translate("interface1", "kilometrage", Q_NULLPTR));
        label_61->setText(QApplication::translate("interface1", "etat", Q_NULLPTR));
        label_62->setText(QApplication::translate("interface1", "tarifs de location", Q_NULLPTR));
        ajouter_vo->setText(QApplication::translate("interface1", "ajouter", Q_NULLPTR));
        modifier_2->setText(QApplication::translate("interface1", "modifier", Q_NULLPTR));
        stat_sarah->setText(QApplication::translate("interface1", "statistiques", Q_NULLPTR));
        pdf_sara->setText(QApplication::translate("interface1", "pdf", Q_NULLPTR));
        qrcode->setText(QApplication::translate("interface1", "QR code", Q_NULLPTR));
        groupBox_9->setTitle(QApplication::translate("interface1", "notifications", Q_NULLPTR));
        OK->setText(QApplication::translate("interface1", "OK", Q_NULLPTR));
        pushButton_20->setText(QApplication::translate("interface1", "cancel", Q_NULLPTR));
        tabWidget_3->setTabText(tabWidget_3->indexOf(tab_13), QApplication::translate("interface1", "ajouter une voiture", Q_NULLPTR));
        label_63->setText(QApplication::translate("interface1", "etat", Q_NULLPTR));
        chercher_sara->setText(QApplication::translate("interface1", "chercher", Q_NULLPTR));
        pushButton_trianne->setText(QApplication::translate("interface1", "tri par annee", Q_NULLPTR));
        tarifs->setText(QApplication::translate("interface1", "tri par tarifs", Q_NULLPTR));
        pushButton_trianne_2->setText(QApplication::translate("interface1", "tri par annee", Q_NULLPTR));
        tabWidget_3->setTabText(tabWidget_3->indexOf(tab_14), QApplication::translate("interface1", "afficher une voiture", Q_NULLPTR));
        groupBox_7->setTitle(QApplication::translate("interface1", "supprimer", Q_NULLPTR));
        label_64->setText(QApplication::translate("interface1", "plaque d'immatriculation", Q_NULLPTR));
        supp_sara->setText(QApplication::translate("interface1", "supprimer", Q_NULLPTR));
        tabWidget_3->setTabText(tabWidget_3->indexOf(tab_15), QApplication::translate("interface1", "supprimer une voiture", Q_NULLPTR));
        groupBox_8->setTitle(QApplication::translate("interface1", "arduino", Q_NULLPTR));
        label_72->setText(QApplication::translate("interface1", "plaque d'immatriculation", Q_NULLPTR));
        aff->setText(QString());
        kilometrage->setText(QApplication::translate("interface1", "kilometrage", Q_NULLPTR));
        tabWidget_3->setTabText(tabWidget_3->indexOf(tab_18), QApplication::translate("interface1", "arduino", Q_NULLPTR));
        pushButton_22->setText(QApplication::translate("interface1", "M", Q_NULLPTR));
        groupBox_4->setTitle(QString());
        label_22->setText(QApplication::translate("interface1", "nom", Q_NULLPTR));
        label_23->setText(QApplication::translate("interface1", "prenom", Q_NULLPTR));
        label_24->setText(QApplication::translate("interface1", "adresse", Q_NULLPTR));
        label_25->setText(QApplication::translate("interface1", "adresse e-mail", Q_NULLPTR));
        label_26->setText(QApplication::translate("interface1", "numpermis", Q_NULLPTR));
        label_27->setText(QApplication::translate("interface1", "naissance", Q_NULLPTR));
        label_28->setText(QApplication::translate("interface1", "numtel", Q_NULLPTR));
        label_29->setText(QApplication::translate("interface1", "numcin", Q_NULLPTR));
        pushButton_10->setText(QApplication::translate("interface1", "ajouter", Q_NULLPTR));
        label_48->setText(QString());
        pushButton_17->setText(QApplication::translate("interface1", "quitter", Q_NULLPTR));
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_7), QApplication::translate("interface1", "ajouter", Q_NULLPTR));
        pushButton_11->setText(QApplication::translate("interface1", "recherche", Q_NULLPTR));
        pushButton_12->setText(QApplication::translate("interface1", "trier", Q_NULLPTR));
        pushButton_13->setText(QApplication::translate("interface1", "pdf", Q_NULLPTR));
        label_49->setText(QString());
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_8), QApplication::translate("interface1", "afficher", Q_NULLPTR));
        label_30->setText(QApplication::translate("interface1", "TextLabel", Q_NULLPTR));
        pushButton_14->setText(QApplication::translate("interface1", "supprimer", Q_NULLPTR));
        label_50->setText(QString());
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_9), QApplication::translate("interface1", "supprimer", Q_NULLPTR));
        groupBox_5->setTitle(QString());
        pushButton_15->setText(QApplication::translate("interface1", "modifier", Q_NULLPTR));
        label_31->setText(QApplication::translate("interface1", "nom", Q_NULLPTR));
        label_32->setText(QApplication::translate("interface1", "prenom", Q_NULLPTR));
        label_33->setText(QApplication::translate("interface1", "adresse", Q_NULLPTR));
        label_34->setText(QApplication::translate("interface1", "adresse e-mail", Q_NULLPTR));
        label_35->setText(QApplication::translate("interface1", "numpermis", Q_NULLPTR));
        label_36->setText(QApplication::translate("interface1", "naissance", Q_NULLPTR));
        label_37->setText(QApplication::translate("interface1", "numtel", Q_NULLPTR));
        label_38->setText(QApplication::translate("interface1", "numcin", Q_NULLPTR));
        label_51->setText(QString());
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_10), QApplication::translate("interface1", "modifier", Q_NULLPTR));
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_11), QApplication::translate("interface1", "stat", Q_NULLPTR));
        pushButton_19->setText(QApplication::translate("interface1", "envoyer", Q_NULLPTR));
        label_54->setText(QApplication::translate("interface1", "numcin du client", Q_NULLPTR));
        label_55->setText(QApplication::translate("interface1", "TextLabel", Q_NULLPTR));
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_12), QApplication::translate("interface1", "Page", Q_NULLPTR));
        groupBox_3->setTitle(QString());
        label->setText(QApplication::translate("interface1", "matricule", Q_NULLPTR));
        label_19->setText(QApplication::translate("interface1", "password", Q_NULLPTR));
        pushButton_5->setText(QApplication::translate("interface1", "confirmer", Q_NULLPTR));
        pushButton_6->setText(QApplication::translate("interface1", "annuler", Q_NULLPTR));
        label_39->setText(QString());
        label_40->setText(QString());
        pushButton_4->setText(QApplication::translate("interface1", "employe", Q_NULLPTR));
        pushButton_9->setText(QApplication::translate("interface1", "client", Q_NULLPTR));
        label_41->setText(QString());
        label_42->setText(QApplication::translate("interface1", "menu", Q_NULLPTR));
        label_43->setText(QString());
        pushButton_18->setText(QApplication::translate("interface1", "quitter", Q_NULLPTR));
        pushButton_21->setText(QApplication::translate("interface1", "voitures", Q_NULLPTR));
        pushButton_23->setText(QApplication::translate("interface1", "Contrat", Q_NULLPTR));
        contrat_a->setText(QApplication::translate("interface1", "contrat", Q_NULLPTR));
        groupBox_10->setTitle(QApplication::translate("interface1", "gestion_contrat", Q_NULLPTR));
        label_44->setText(QApplication::translate("interface1", "id", Q_NULLPTR));
        label_65->setText(QApplication::translate("interface1", "montant", Q_NULLPTR));
        label_66->setText(QApplication::translate("interface1", "date debut", Q_NULLPTR));
        label_67->setText(QApplication::translate("interface1", "date fin", Q_NULLPTR));
        ajouter->setText(QApplication::translate("interface1", "ajouter", Q_NULLPTR));
        modifier->setText(QApplication::translate("interface1", "modifier", Q_NULLPTR));
        supprimer->setText(QApplication::translate("interface1", "supprimer", Q_NULLPTR));
        afficher->setText(QApplication::translate("interface1", "afficher", Q_NULLPTR));
        pdf->setText(QApplication::translate("interface1", "pdf", Q_NULLPTR));
        stattt->setText(QApplication::translate("interface1", "stat", Q_NULLPTR));
        tri_3->setText(QString());
        chercher->setPlaceholderText(QApplication::translate("interface1", "tapez ici", Q_NULLPTR));
        historique->setText(QApplication::translate("interface1", "historique", Q_NULLPTR));
        tri_2->setText(QApplication::translate("interface1", "send to Ar", Q_NULLPTR));
        tri->setText(QApplication::translate("interface1", "tri", Q_NULLPTR));
        label_68->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class interface1: public Ui_interface1 {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_INTERFACE1_H
